version: '3.5'

services:

  eventstore:
    container_name: marketplace-eventstore
    image: eventstore/eventstore
    ports:
      - 2113:2113
      - 1113:1113
    environment:
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INT_TCP_PORT=1113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true

  ravendb:
    container_name: marketplace-ch11-ravendb
    image: ravendb/ravendb
    ports:
      - 8080:8080
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_ARGS="--Setup.Mode=None"
